In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Dataset/customer_shopping_behavior.csv")

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [9]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x :x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [13]:
# create a columns age_group
lables = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels=lables)

In [14]:
df[['age','age_group']]

      age    age_group
0      55  Middle-aged
1      19  Young Adult
2      50  Middle-aged
3      21  Young Adult
4      45  Middle-aged
...   ...          ...
3895   40        Adult
3896   52  Middle-aged
3897   46  Middle-aged
3898   44        Adult
3899   52  Middle-aged

[3900 rows x 2 columns]

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group'],
      dtype='str')

In [16]:
df['frequency_of_purchases'].unique()

<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [17]:
# create column purchase_frequency_days
frequency_mapping = {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [18]:
df[['frequency_of_purchases','purchase_frequency_days']]

     frequency_of_purchases  purchase_frequency_days
0               Fortnightly                       14
1               Fortnightly                       14
2                    Weekly                        7
3                    Weekly                        7
4                  Annually                      365
...                     ...                      ...
3895                 Weekly                        7
3896              Bi-Weekly                       14
3897              Quarterly                       90
3898                 Weekly                        7
3899              Quarterly                       90

[3900 rows x 2 columns]

In [19]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [20]:
df=df.drop('promo_code_used',axis=1)

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [22]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
# mysql connection
username ='root'
password = 'Amisha@2005'
host = 'localhost'
port ='3306'
database = 'customer_behavior'

engine = create_engine(
    "mysql+pymysql://root:Amisha%402005@localhost/customer_behavior"
)
# write dataframe to mysql
table_name = 'customer'#choose any table name
df.to_sql(table_name,engine,if_exists='replace',index=False)
# Read back sample
pd.read_sql("select * from customer limit 5;",engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [23]:
# q1.what is the total revenue generated by male vs female customers?
pd.read_sql('SELECT gender,SUM(purchase_amount) as revenue FROM customer GROUP BY gender',engine)

   gender   revenue
0    Male  157890.0
1  Female   75191.0

In [24]:
# q2 which customers used a discount but still spent more than the average purchase amount
pd.read_sql("SELECT customer_id,purchase_amount FROM customer WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer) ",engine)

     customer_id  purchase_amount
0              2               64
1              3               73
2              4               90
3              7               85
4              9               97
..           ...              ...
834         1667               64
835         1671               73
836         1673               73
837         1674               62
838         1676               90

[839 rows x 2 columns]

In [25]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [26]:
# q3 which are the top 5 products with the highest average review 
pd.read_sql("SELECT item_purchased , ROUND(AVG(review_rating),2) as 'Average Product review rating' FROM customer GROUP BY item_purchased ORDER BY AVG(review_rating) DESC LIMIT 5 ",engine)

  item_purchased  Average Product review rating
0         Gloves                           3.86
1        Sandals                           3.84
2          Boots                           3.82
3            Hat                           3.80
4          Skirt                           3.78

In [27]:
df['shipping_type'].unique()

<StringArray>
[       'Express',  'Free Shipping',   'Next Day Air',       'Standard',
 '2-Day Shipping',   'Store Pickup']
Length: 6, dtype: str

In [28]:
# q4 compare the average purchase amounts between standard and express shipping
pd.read_sql('SELECT shipping_type,ROUND(AVG(purchase_amount),2) FROM customer WHERE shipping_type IN("Standard","Express") GROUP BY shipping_type',engine)

  shipping_type  ROUND(AVG(purchase_amount),2)
0       Express                          60.48
1      Standard                          58.46

In [29]:
# q5 do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers,
pd.read_sql("SELECT subscription_status,COUNT(customer_id) AS customers,AVG(purchase_amount) AS avg_spend,SUM(purchase_amount) AS total_revenue FROM customer GROUP BY subscription_status ORDER BY total_revenue,avg_spend DESC ",engine)

  subscription_status  customers  avg_spend  total_revenue
0                 Yes       1053    59.4919        62645.0
1                  No       2847    59.8651       170436.0

In [30]:
#q6 which 5 products have the highest percentage of purchases with discounts applied?
pd.read_sql("SELECT item_purchased,ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) AS discount_rate FROM customer GROUP BY item_purchased ORDER BY discount_rate DESC LIMIT 5;",engine)

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

In [31]:
#q7 segment customers into new ,returning , and loyal based on their total number of previous purchase and show the count of each segment.
pd.read_sql("with customer_type as (SELECT customer_id ,previous_purchases, CASE WHEN  previous_purchases =1 THEN 'New' WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Retutning' ELSE 'Loyal' END AS customer_segment FROM customer) SELECT customer_segment, COUNT(*) AS 'number_of_customer' FROM customer_type GROUP BY customer_segment",engine)

  customer_segment  number_of_customer
0            Loyal                3116
1        Retutning                 701
2              New                  83

In [32]:
# q8 what are the top 3 most purchased products with in each category?
pd.read_sql("WITH item_count AS (SELECT category,item_purchased,COUNT(customer_id)AS total_orders  ,ROW_NUMBER() OVER( PARTITION BY category  ORDER BY COUNT(customer_id) DESC) AS item_rank FROM customer GROUP BY category,item_purchased) SELECT item_rank,category,item_purchased,total_orders FROM item_count WHERE item_rank <=3 ",engine)

    item_rank     category item_purchased  total_orders
0           1  Accessories        Jewelry           171
1           2  Accessories     Sunglasses           161
2           3  Accessories           Belt           161
3           1     Clothing         Blouse           171
4           2     Clothing          Pants           171
5           3     Clothing          Shirt           169
6           1     Footwear        Sandals           160
7           2     Footwear          Shoes           150
8           3     Footwear       Sneakers           145
9           1    Outerwear         Jacket           163
10          2    Outerwear           Coat           161

In [33]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [35]:
# q9 are customers who are repeat buyers(more than 5 previous purchases)also likely to subscribe?
pd.read_sql("SELECT subscription_status , COUNT(customer_id) AS repeat_buyers FROM customer WHERE previous_purchases > 5 GROUP BY subscription_status ",engine)

  subscription_status  repeat_buyers
0                 Yes            958
1                  No           2518

In [39]:
# q10 what is the revenue contribution of each age group 
pd.read_sql("SELECT age_group , SUM(purchase_amount) as revenue FROM customer GROUP BY age_group ORDER BY revenue DESC",engine)

     age_group  revenue
0  Young Adult  62143.0
1  Middle-aged  59197.0
2        Adult  55978.0
3       Senior  55763.0